### ISSUE TITLE
PHP SDK ParseError: syntax error, unexpected 'IdGenerator'

### ISSUE THREAD

**Issue by ssuui** [yedf/dtmcli-php#1]
- php version : 7.3
 - repetition frequency : every time
 - error
  - file : \\vendor\yedf\dtmcli-php\src\Tcc.php
  - line : 9
  - message:ParseError: syntax error, unexpected 'IdGenerator'
  
老哥你用的该不会是PHP方言版的语法糖吧.还是8的?我这版本很高了.你这写法跟强类型的感觉差不多了.

**Comment by onlyshow** [comment]
php7.4的语法糖
